### ISSUE TITLE
请问支持其他模型么，比如llama2

### ISSUE THREAD

**Issue by Stephen-SMJ** [yuanjie-ai/ChatLLM#10]

**Comment by yuanjie-ai** [comment]
可以把其他模型部署成服务接入



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Sun Maojun ***@***.***&gt;
发送时间: 2023年10月12日 10:53
收件人: yuanjie-ai/ChatLLM ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yuanjie-ai/ChatLLM] 请问支持其他模型么，比如llama2 (Issue #10)

**Comment by yuanjie-ai** [comment]
恩

**Comment by yuanjie-ai** [comment]
1
