### ISSUE TITLE
demo文件有点问题，没跑通

### ISSUE THREAD

**Issue by dhhcj** [yuanjie-ai/ChatLLM#3]
首先是方法名引用错了
![image](https://user-images.githubusercontent.com/26632100/234816659-6a34cc99-fc4e-43df-8cc5-ccaad9b2edef.png)
模型文件，我使用的是本地的路径
文本文件，我用的是./data, 我不确定这么加载对不对
![image](https://user-images.githubusercontent.com/26632100/234816973-cec45f97-a48b-41d9-90cb-3543effa40a9.png)
读取query的时候报错了
![image](https://user-images.githubusercontent.com/26632100/234817231-cf714304-1a34-4bfe-a8ee-4b268bf37b4b.png)

**Comment by yuanjie-ai** [comment]
from chatllm.applications import ChatBase

qa = ChatBase()
qa.load_llm4chat(model_name_or_path="/Users/betterme/PycharmProjects/AI/CHAT_MODEL/chatglm")

for i, _ in qa(query='周杰伦是谁', knowledge_base='周杰伦是傻子'):
    pass

for i, _ in qa(query='你是谁', knowledge_base=''):
    pass

**Comment by yuanjie-ai** [comment]
用最新代码
```python
from chatllm.applications import ChatBase

qa = ChatBase()
qa.load_llm4chat(model_name_or_path="/Users/betterme/PycharmProjects/AI/CHAT_MODEL/chatglm")

for i, _ in qa(query='周杰伦是谁', knowledge_base='周杰伦是傻子'):
    pass

for i, _ in qa(query='你是谁', knowledge_base=''):
    pass
```

**Comment by yuanjie-ai** [comment]
> 首先是方法名引用错了 ![image](https://user-images.githubusercontent.com/26632100/234816659-6a34cc99-fc4e-43df-8cc5-ccaad9b2edef.png) 模型文件，我使用的是本地的路径 文本文件，我用的是./data, 我不确定这么加载对不对 ![image](https://user-images.githubusercontent.com/26632100/234816973-cec45f97-a48b-41d9-90cb-3543effa40a9.png) 读取query的时候报错了 ![image](https://user-images.githubusercontent.com/26632100/234817231-cf714304-1a34-4bfe-a8ee-4b268bf37b4b.png)

用最新代码
