### ISSUE TITLE
Can't pickle local object 'ChatANN.create_index.<locals>.<lambda>'

### ISSUE THREAD

**Issue by Shun-Calvin** [yuanjie-ai/ChatLLM#5]
![image](https://github.com/yuanjie-ai/ChatLLM/assets/67963974/f6672efd-c4a8-4cc6-9628-1b01e08f7eb9)

**Comment by yuanjie-ai** [comment]
删掉pdf_cache文件夹，然后重试



发自我的iPhone


------------------ Original ------------------
From: Calvin_Shun ***@***.***&gt;
Date: Sat,May 13,2023 6:56 PM
To: yuanjie-ai/ChatLLM ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [yuanjie-ai/ChatLLM] Can't pickle local object'ChatANN.create_index.<locals&gt;.<lambda&gt;' (Issue #5)

**Comment by Shun-Calvin** [comment]
> 删掉pdf_cache文件夹，然后重试 发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: Calvin_Shun ***@***.***&gt; Date: Sat,May 13,2023 6:56 PM To: yuanjie-ai/ChatLLM ***@***.***&gt; Cc: Subscribed ***@***.***&gt; Subject: Re: [yuanjie-ai/ChatLLM] Can't pickle local object'ChatANN.create_index.<locals&gt;.<lambda&gt;' (Issue #5)

还是一样，把 pdf_cache 删了也是一样报错，整个档案删掉再下载也是一样的错误

**Comment by yuanjie-ai** [comment]
我明天修一下



发自我的iPhone


------------------ Original ------------------
From: Calvin_Shun ***@***.***&gt;
Date: Sat,May 13,2023 7:11 PM
To: yuanjie-ai/ChatLLM ***@***.***&gt;
Cc: Betterme ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [yuanjie-ai/ChatLLM] Can't pickle local object'ChatANN.create_index.<locals&gt;.<lambda&gt;' (Issue #5)





  
删掉pdf_cache文件夹，然后重试 发自我的iPhone
 …
 ------------------ Original ------------------ From: Calvin_Shun @.&gt; Date: Sat,May 13,2023 6:56 PM To: yuanjie-ai/ChatLLM @.&gt; Cc: Subscribed @.***&gt; Subject: Re: [yuanjie-ai/ChatLLM] Can't pickle local object'ChatANN.create_index.<locals&gt;.<lambda&gt;' (Issue #5)
  
还是一样，把 pdf_cache 删了也是一样报错，整个档案删掉再下载也是一样的错误

**Comment by yuanjie-ai** [comment]
更新下pip install meutils -U好像是pickle版本的问题



发自我的iPhone


------------------ Original ------------------
From: Calvin_Shun ***@***.***&gt;
Date: Sat,May 13,2023 6:56 PM
To: yuanjie-ai/ChatLLM ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [yuanjie-ai/ChatLLM] Can't pickle local object'ChatANN.create_index.<locals&gt;.<lambda&gt;' (Issue #5)

**Comment by Shun-Calvin** [comment]
更新到最新（应该是2023.5.12.18.5.27 ），还是报一样的错误，而且我试了把data内的財報放进去测试，pdf_cache内的pkl是0 KB的

**Comment by yuanjie-ai** [comment]
已修复，请更新
```
pip install "chatllm[pdf]"  -U && chatllm-run webui --name chatpdf

```
