### ISSUE TITLE
你好，有关于文档内容抽取的实现？

### ISSUE THREAD

**Issue by zhengorange** [yuanjie-ai/ChatLLM#9]
从你的介绍中可以看到你通过句法模版抽取引擎、开放域抽取系统等对文档进行处理，很想借鉴你的实现，可是没有在你的代码中没有找到相关的实现。
![截屏2023-09-04 09 49 33](https://github.com/yuanjie-ai/ChatLLM/assets/51870856/5412b297-789d-4d52-950a-b8a867aeeab9)

**Comment by yuanjie-ai** [comment]
参考unstructured这个包



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: superLazy ***@***.***&gt;
发送时间: 2023年9月4日 09:54
收件人: yuanjie-ai/ChatLLM ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [yuanjie-ai/ChatLLM] 你好，有关于文档内容抽取的实现？ (Issue #9)
